// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameCatalogue.Data;

#nullable disable

namespace VideoGameCatalogue.Data.Migrations
{
    [DbContext(typeof(VideoGameCatalogueContext))]
    [Migration("20260212210842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameCatalogue.Core.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A free-to-play tactical shooter developed by Riot Games.",
                            Genre = "First-Person Shooter",
                            Platform = "PC",
                            Price = 0.00m,
                            Rating = 8.5,
                            ReleaseDate = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Valorant"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "MOBA",
                            Platform = "PC",
                            Price = 0.00m,
                            Rating = 8.0,
                            ReleaseDate = new DateTime(2009, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "League of Legends"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A turn-based RPG inspired by French art and culture.",
                            Genre = "RPG",
                            Platform = "PC",
                            Price = 49.99m,
                            Rating = 9.0,
                            ReleaseDate = new DateTime(2025, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clair Obscur: Expedition 33"
                        },
                        new
                        {
                            Id = 4,
                            Description = "An open-world action RPG created by FromSoftware and George R.R. Martin.",
                            Genre = "RPG",
                            Platform = "PC",
                            Price = 59.99m,
                            Rating = 9.8000000000000007,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
